/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MovieDTO } from '../model/models';
import { ProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MoviesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new movie
     * Creates a new movie with associated actors. Actors are created if they don\&#39;t exist.
     * @param movieDTO 
     */
    createMovie(movieDTO: MovieDTO, extraHttpRequestParams?: any): Observable<MovieDTO>;

    /**
     * Delete a movie
     * Deletes a movie and removes all actor associations
     * @param id Movie ID
     */
    deleteMovie(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get movie by name
     * Retrieves a specific movie by its exact name
     * @param name Movie name
     */
    getMovieByName(name: string, extraHttpRequestParams?: any): Observable<MovieDTO>;

    /**
     * Search movies
     * Retrieves all movies, optionally filtered by publication date range. If only startDate is provided, endDate defaults to today.
     * @param name 
     * @param startDate 
     * @param endDate 
     */
    searchMovies(name?: string, startDate?: string, endDate?: string, extraHttpRequestParams?: any): Observable<Array<MovieDTO>>;

    /**
     * Update a movie
     * Updates an existing movie and synchronizes its actor associations
     * @param id Movie ID
     * @param movieDTO 
     */
    updateMovie(id: number, movieDTO: MovieDTO, extraHttpRequestParams?: any): Observable<MovieDTO>;

}
